### ISSUE TITLE
Warnings during coverage run

### ISSUE THREAD

**Issue by bchew** [Adslot/adslot-ui#845]
## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [x] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

## Description
Warnings seem to have crept into coverage runs on master (not in exact order, copying and pasting them from recent coverage run log on master):
```
06 05 2019 01:56:52.468:WARN [web-server]: 404: /assets/svg-symbols.svg
06 05 2019 01:56:52.635:WARN [web-server]: 404: /path/to/image-0.jpg
06 05 2019 01:56:52.635:WARN [web-server]: 404: /path/to/image-1.jpg
06 05 2019 01:56:52.637:WARN [web-server]: 404: /path/to/image-2.jpg
06 05 2019 01:56:52.639:WARN [web-server]: 404: /path/to/image-3.jpg
06 05 2019 01:56:52.640:WARN [web-server]: 404: /path/to/image-4.jpg
ERROR: 'Warning: Failed prop type: Invalid prop `checked` of value `test` supplied to `Checkbox`, expected one of [true,false,"partial"].
    in Checkbox'
```

E.g. https://travis-ci.org/Adslot/adslot-ui/jobs/528605823#L530

**Comment by nimishjha** [comment]
The error is being thrown by a test that deliberately passes an invalid prop to the Checkbox component to see if it throws an error. This test should probably be removed, as that's what propTypes are for. The warnings are caused by tests that reference images that don't exist, so they're not really a problem.
